### ISSUE TITLE
Set the event time

### ISSUE THREAD

**Issue by pppaapp** [andrewbrereton/obsidian-to-ical-plugin#24]
When creating a task with [Day planner](https://github.com/ivan-lednev/obsidian-day-planner), the text is prefixed with time

![CleanShot 2023-12-01 at 21 40 56](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/1868da2a-dc3c-4214-a1d2-261717f7fd0e)

It would be nice to set this to the event time

**Comment by andrewbrereton** [comment]
I think I could add support for Day Planner plugin format.

![image](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/682893/300b331e-bc14-4bfe-bb74-dbf228a90905)

I can see from the above screenshot that there appear to be two formats. I will need to dig through the code to get a good understanding of this plugin so that iCal is able to properly detect a Day Planner file and parse it correctly.

**Comment by andrewbrereton** [comment]
Hi all. This has been addressed in release [1.18.0](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.18.0).

Please update the plugin and then enable the new setting `Support Day Planner plugin?`.

I have updated the tests to check for all sorts of time formats, however I would not be surprised if there are some issues. So if you see things like the wrong start time, or end time, or missing events, please let me know.
