### ISSUE TITLE
recurring export doesn't work

### ISSUE THREAD

**Issue by bepolymathe** [andrewbrereton/obsidian-to-ical-plugin#27]
Hi @andrewbrereton 

First of all, thank you for this plugin. I've been waiting for this for a long time and it's a turning point for me. I want to export to local (.ics) for reading via thunderbird. 
If I make a parameter change, the export goes well the first time but after 5 min (default time) the update doesn't work. I get no error message in the obsidian console. 🤔

**Comment by andrewbrereton** [comment]
Hi @bepolymathe, this _may_ be resolved in [1.9.3](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.9.3). This release changes the initial starting call from `onload` to `onLayoutReady` as I was seeing a similar issue (#33).

I'm curious if the fix for #33 has also fixed this issue.
